["PARAMETER"]
additionalModels="VSADSSMINI_2020_LV95_Validierung_IPW_20230207"

##
## Constraint-Warnungen für Knoten
##

# Finanzierung
["VSADSSMINI_2020_LV95_Validierung_IPW_20230207.VSADSSMini_Validierung.v_Knoten.11012"]
check="warning"

# Status
["VSADSSMINI_2020_LV95_Validierung_IPW_20230207.VSADSSMini_Validierung.v_Knoten.11025"]
check="warning"

##
## Constraint-Warnungen für Leitungen
##

# Finanzierung
["VSADSSMINI_2020_LV95_Validierung_IPW_20230207.VSADSSMini_Validierung.v_Leitung.12007"]
check="warning"

# Nutzungsart_Ist
["VSADSSMINI_2020_LV95_Validierung_IPW_20230207.VSADSSMini_Validierung.v_Leitung.12025"]
check="warning"

# Status
["VSADSSMINI_2020_LV95_Validierung_IPW_20230207.VSADSSMini_Validierung.v_Leitung.12035"]
check="warning"

##
## Validierung Rohrprofil deaktivieren
##

# Bezeichnung
["VSADSSMINI_2020_LV95.VSADSSMini.Rohrprofil.Bezeichnung"]
multiplicity="off"

# Unique Constraint
["VSADSSMINI_2020_LV95.VSADSSMini.Rohrprofil.Constraint1"]
check="off"

##
## Validierung Ueberlauf_Foerderaggregat deaktivieren
##

# Bezeichnung
["VSADSSMINI_2020_LV95.VSADSSMini.Ueberlauf_Foerderaggregat.Bezeichnung"]
multiplicity="off"

# Unique Constraint
["VSADSSMINI_2020_LV95.VSADSSMini.Ueberlauf_Foerderaggregat.Constraint1"]
check="off"

# Rolle 1
["VSADSSMINI_2020_LV95.VSADSSMini.Ueberlauf_Foerderaggregat_KnotenAssoc.KnotenRef"]
multiplicity="off"

# Rolle 2
["VSADSSMINI_2020_LV95.VSADSSMini.Ueberlauf_Foerderaggregat_Knoten_nachAssoc.Knoten_nachRef"]
multiplicity="off"

##
## Validierung Teileinzugsgebiet deaktivieren
##

# Bezeichnung
["VSADSSMINI_2020_LV95.VSADSSMini.Teileinzugsgebiet.Bezeichnung"]
multiplicity="off"

# Unique Constraint
["VSADSSMINI_2020_LV95.VSADSSMini.Teileinzugsgebiet.Constraint1"]
check="off"

