name: ipwvalidator

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      BUILD_NUMBER: ${{ github.run_number }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew clean functionalTests:build

      - uses: actions/upload-artifact@v2
        #if: ${{ failure() }}
        with:
          name: reports
          path: functionalTests/build/reports/tests/
